import { useEffect, useRef, useState } from "react";

const API_BASE = import.meta.env.VITE_API_BASE_URL ?? "";

const EVENT_HINTS = {
  observation: "Pool wait time is isolated to the primary zone",
  action: "Shifted 20 percent of traffic to the healthy pool",
  constraint: "Do not restart the database until the snapshot completes",
  hypothesis: "A leaked client is exhausting the pool",
};

const FAQS = [
  ["Is this only a chat history wrapper?", "No. Relay reads persisted incident state before choosing an action. Failed remediation and operator constraints materially change the next recommendation."],
  ["What happens without Sibyl Memory?", "A fresh responder loses the failed restart and the database constraint, then falls back to the same restart that already produced no improvement."],
  ["Is the fresh session real?", "Yes. Relay creates a new session identifier, reloads the incident memories and writes a visible receipt to the journal."],
  ["Can a responder add new evidence?", "Yes. Observations, actions, constraints and hypotheses can be persisted while the incident is active. The recommendation is recomputed after each write."],
  ["Which memory primitives are used?", "Relay uses a durable incident entity, HOT active state and COLD journal events through the real Sibyl Memory client."],
  ["Is the recommendation generated by an external model?", "No. This prototype uses deterministic decision logic so the causal effect of memory stays reproducible without a model key."],
];

const FALLBACK_INCIDENT = {
  id: "INC 204",
  title: "Checkout latency spike",
  service: "checkout API",
  severity: "SEV 1",
  status: "investigating",
  impact: "31 percent of checkout requests exceed 2.5 seconds",
  attempted_actions: [{ action: "Restart checkout API", result: "no improvement" }],
};

async function request(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, {
    headers: { "Content-Type": "application/json", ...(options.headers ?? {}) },
    ...options,
  });
  if (!response.ok) {
    const body = await response.json().catch(() => ({}));
    throw new Error(body.detail || `Request failed with ${response.status}`);
  }
  return response.json();
}

function cleanCopy(value = "") {
  return String(value).replaceAll("-", " ").replaceAll("_", " ");
}

function formatTime(value) {
  if (!value) return "Unknown time";
  return new Intl.DateTimeFormat("en", {
    hour: "2-digit",
    minute: "2-digit",
    hour12: false,
    timeZone: "UTC",
  }).format(new Date(value));
}

function useRevealMotion() {
  useEffect(() => {
    const nodes = [...document.querySelectorAll("[data-reveal]")];
    const observer = new IntersectionObserver((entries) => {
      entries.forEach((entry) => {
        if (entry.isIntersecting) {
          entry.target.classList.add("is-visible");
          observer.unobserve(entry.target);
        }
      });
    }, { threshold: 0.14 });
    nodes.forEach((node) => observer.observe(node));
    return () => observer.disconnect();
  }, []);
}

function Brand() {
  return <span className="brand-lockup"><span className="brand-sigil" aria-hidden="true">R</span><strong>RELAY</strong></span>;
}

function SiteNav({ onRun }) {
  const [open, setOpen] = useState(false);
  const firstLink = useRef(null);

  useEffect(() => {
    if (!open) return undefined;
    const priorOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    firstLink.current?.focus();
    const closeOnEscape = (event) => { if (event.key === "Escape") setOpen(false); };
    window.addEventListener("keydown", closeOnEscape);
    return () => {
      document.body.style.overflow = priorOverflow;
      window.removeEventListener("keydown", closeOnEscape);
    };
  }, [open]);

  const close = () => setOpen(false);

  return (
    <header className="site-header">
      <nav className="nav-pill" aria-label="Main navigation">
        <a href="#top" className="brand-link" aria-label="Relay home" onClick={close}><Brand /></a>
        <div className="desktop-nav"><a href="#product">Product</a><a href="#proof">Proof</a><a href="#faq">FAQ</a></div>
        <button className="nav-action" onClick={onRun}>Run the memory test <span aria-hidden="true">→</span></button>
        <button className={`menu-toggle ${open ? "is-open" : ""}`} aria-label={open ? "Close menu" : "Open menu"} aria-expanded={open} aria-controls="mobile-menu" onClick={() => setOpen((value) => !value)}><span /><span /></button>
      </nav>
      <div id="mobile-menu" className={`mobile-menu ${open ? "is-open" : ""}`} aria-hidden={!open}>
        <a ref={firstLink} href="#product" onClick={close}>Product</a><a href="#proof" onClick={close}>Proof</a><a href="#faq" onClick={close}>FAQ</a>
        <button onClick={() => { close(); onRun(); }}>Run the memory test <span aria-hidden="true">→</span></button>
      </div>
    </header>
  );
}

function StatusDot({ tone = "blue" }) {
  return <span className={`status-dot status-${tone}`} aria-hidden="true" />;
}

function HeroConsole({ data, loading }) {
  const incident = data?.incident ?? FALLBACK_INCIDENT;
  const memories = data?.memories ?? [];
  const recommendation = data?.recommendation;
  const attempt = incident.attempted_actions?.[0];
  const shownMemories = memories.length ? memories.slice(-2) : [
    { label: "Operator constraint", detail: "Database restart blocked until snapshot completes" },
    { label: "Leading hypothesis", detail: "Connection pool exhaustion after deploy" },
  ];

  return (
    <div className="hero-console" aria-label="Live Relay incident preview" aria-busy={loading}>
      <div className="console-topline"><span className="console-title"><span aria-hidden="true">›_</span> Relay console</span><span className="live-state"><StatusDot tone="green" />Live memory</span></div>
      <div className="hero-console-body">
        <section className="hero-incident">
          <p className="console-label">Active incident</p>
          <div className="hero-incident-title">
            <div><span className="mono muted">{cleanCopy(incident.severity)} · {cleanCopy(incident.service)}</span><h2>{cleanCopy(incident.title)}</h2></div>
            <span className="state-chip"><StatusDot tone="red" />{cleanCopy(incident.status)}</span>
          </div>
          <p className="impact-line">{cleanCopy(incident.impact)}</p>
          <p className="console-label memory-label">What Relay remembers</p>
          <div className="preview-memory-list">
            <div className="preview-memory is-failed"><span className="memory-index mono">01</span><span><strong>{cleanCopy(attempt?.action ?? "Restart checkout API")}</strong><small>{cleanCopy(attempt?.result ?? "no improvement")}</small></span></div>
            {shownMemories.map((memory, index) => <div className="preview-memory" key={`${memory.label}-${index}`}><span className="memory-index mono">0{index + 2}</span><span><strong>{cleanCopy(memory.label)}</strong><small>{cleanCopy(memory.detail)}</small></span></div>)}
          </div>
        </section>
        <section className="hero-decision">
          <div><p className="console-label">Grounded recommendation</p><h3>{cleanCopy(recommendation?.action ?? "Waiting for incident memory")}</h3><p>{cleanCopy(recommendation?.rationale ?? "Relay is loading the persisted evidence before choosing a next action.")}</p></div>
          <div className={`receipt-preview ${data?.is_fresh_session ? "is-active" : ""}`}><span className="receipt-check" aria-hidden="true">✓</span><span><strong>{data?.is_fresh_session ? "Fresh session receipt" : "Receipt ready after test"}</strong><small className="mono">{cleanCopy(data?.session_id ?? "new session pending")}</small></span></div>
        </section>
      </div>
    </div>
  );
}

function Hero({ data, loading, onRun }) {
  return (
    <section className="hero page-width" id="top" aria-labelledby="hero-title">
      <div className="hero-copy" data-reveal><p className="eyebrow">Operational memory for AI responders</p><h1 id="hero-title">The next responder already knows what failed.</h1><p className="hero-subhead">Relay gives incident response agents operational memory. A fresh session recalls failed remediation, operator constraints and live hypotheses before it recommends the next action.</p><button className="primary-action" onClick={onRun}>Run the memory test <span aria-hidden="true">→</span></button><p className="proof-line"><span className="sibyl-mark" aria-hidden="true">S</span><span>Built on <strong>Sibyl Memory</strong> with a visible fresh session receipt.</span></p></div>
      <div className="hero-media" data-reveal><HeroConsole data={data} loading={loading} /></div>
    </section>
  );
}

function ProblemSection({ data }) {
  const stateless = cleanCopy(data?.stateless_recommendation ?? "Restart checkout API, then watch p95 latency for five minutes.");
  const recalled = cleanCopy(data?.recommendation?.action ?? "Shift traffic to the healthy pool and capture evidence before changing capacity.");
  return (
    <section className="story-section page-width" id="product" aria-labelledby="problem-title">
      <div className="section-intro" data-reveal><p className="eyebrow">The handoff problem</p><h2 id="problem-title">Stateless responders repeat the incident.</h2><p>Fresh sessions start from zero. Prior failures disappear, safety constraints get asked for again and the investigation loops.</p></div>
      <div className="comparison-panels" data-reveal>
        <article className="comparison-panel is-stateless"><span className="comparison-status"><StatusDot tone="red" />Blank fresh session</span><p className="comparison-action">{stateless}</p><ul><li>Asks for context again</li><li>Misses operator constraints</li><li>Repeats a failed suggestion</li></ul></article>
        <article className="comparison-panel is-recalled"><span className="comparison-status"><StatusDot tone="blue" />Relay recall</span><p className="comparison-action">{recalled}</p><ul><li>Loads the latest useful truth</li><li>Respects the active constraint</li><li>Grounds the next action</li></ul></article>
      </div>
      <div className="benefit-rows" aria-label="Memory benefits">
        <article className="benefit-row" data-reveal><span className="benefit-number mono">01</span><div><h3>Recall the failure</h3><p>Bring forward what was tried, observed and verified.</p></div><code>outcome: no improvement</code></article>
        <article className="benefit-row" data-reveal><span className="benefit-number mono">02</span><div><h3>Respect the constraint</h3><p>Surface the operational guardrails that shape every decision.</p></div><code>limit: database snapshot</code></article>
        <article className="benefit-row" data-reveal><span className="benefit-number mono">03</span><div><h3>Continue the hypothesis</h3><p>Carry forward the live thread of reasoning without rehashing.</p></div><code>signal: pool exhaustion</code></article>
      </div>
    </section>
  );
}

function TaglineReveal() {
  const words = "Every fresh session should start with the last useful truth.".split(" ");
  return <section className="tagline page-width" aria-label="Relay promise" data-reveal><p>{words.map((word, index) => <span key={`${word}-${index}`} style={{ "--word-index": index }}>{word}{index < words.length - 1 ? " " : ""}</span>)}</p></section>;
}

function HowItWorks() {
  return (
    <section className="how-section page-width" aria-labelledby="how-title">
      <div className="section-intro" data-reveal><p className="eyebrow">The memory loop</p><h2 id="how-title">How Relay works</h2></div>
      <ol className="process-list">
        <li data-reveal><span className="process-index mono">01</span><h3>Record evidence</h3><p>Relay writes observations, actions, constraints and hypotheses as the incident changes.</p><code>set entity + write event</code></li>
        <li data-reveal><span className="process-index mono">02</span><h3>Retrieve what matters</h3><p>A new responder recalls the durable incident, active state and relevant journal events.</p><code>HOT + WARM + COLD</code></li>
        <li data-reveal><span className="process-index mono">03</span><h3>Return a receipt</h3><p>The fresh session shows which memories loaded before Relay recomputed the action.</p><code>status: ready</code></li>
      </ol>
    </section>
  );
}

function MemoryTier({ tier }) {
  return <span className={`tier tier-${String(tier).toLowerCase()}`}>{cleanCopy(tier)}</span>;
}

function DemoConsole({ data, loading, error, pending, onRun, onReset, onRetry, onAddEvent }) {
  const [view, setView] = useState("memory");
  const [eventKind, setEventKind] = useState("observation");
  const [eventSummary, setEventSummary] = useState("");
  const [eventOutcome, setEventOutcome] = useState("");
  const incident = data?.incident ?? FALLBACK_INCIDENT;
  const memories = data?.memories ?? [];
  const journal = data?.journal ?? [];
  const recommendation = data?.recommendation;

  useEffect(() => {
    if (data?.is_fresh_session) setView("receipt");
  }, [data?.is_fresh_session, data?.session_id]);

  const submit = async (event) => {
    event.preventDefault();
    if (eventSummary.trim().length < 3) return;
    const saved = await onAddEvent({ kind: eventKind, summary: eventSummary.trim(), outcome: eventKind === "action" ? eventOutcome.trim() || "completed" : null, confidence: eventKind === "hypothesis" ? 0.65 : null });
    if (saved) { setEventSummary(""); setEventOutcome(""); }
  };

  return (
    <section className="demo-shell" id="demo" aria-labelledby="demo-title">
      <div className="demo-toolbar"><div><span className="console-title"><span aria-hidden="true">›_</span> Relay console</span><span className="live-state"><StatusDot tone={error ? "red" : "green"} />{error ? "Connection interrupted" : loading ? "Opening memory" : "Active incident"}</span></div><div className="toolbar-actions"><button className="secondary-action" onClick={onReset} disabled={Boolean(pending)}>Reset incident</button><button className="primary-action compact" onClick={onRun} disabled={Boolean(pending) || loading}>{pending === "session" ? "Recalling memory" : "Run the memory test"}</button></div></div>
      {error ? <div className="inline-message is-error" role="alert"><span><strong>Relay could not complete that request.</strong> {error}</span><button onClick={onRetry}>Try again</button></div> : null}
      <div className="demo-tabs" role="tablist" aria-label="Console views">{[["incident", "Incident"], ["memory", "Memory"], ["receipt", "Receipt"]].map(([id, label]) => <button key={id} role="tab" aria-selected={view === id} onClick={() => setView(id)}>{label}</button>)}</div>
      <div className="demo-grid" data-mobile-view={view}>
        <section className="demo-panel timeline-panel" data-view="incident" aria-labelledby="timeline-title"><div className="panel-heading"><h3 id="timeline-title">Incident timeline</h3><span className="mono">{cleanCopy(incident.id)}</span></div><div className="incident-summary"><span><StatusDot tone="red" />{cleanCopy(incident.severity)}</span><strong>{cleanCopy(incident.title)}</strong><p>{cleanCopy(incident.impact)}</p></div><ol className="timeline-list">{journal.slice(0, 6).map((entry) => <li key={entry.id}><time className="mono" dateTime={entry.timestamp}>{formatTime(entry.timestamp)} UTC</time><div><span>{cleanCopy(entry.kind)}</span><p>{cleanCopy(entry.summary)}</p>{entry.outcome ? <small>Outcome: {cleanCopy(entry.outcome)}</small> : null}</div></li>)}{!journal.length ? <li className="empty-row">The journal will appear when memory is connected.</li> : null}</ol></section>
        <section className="demo-panel memory-panel" data-view="memory" aria-labelledby="memories-title"><div className="panel-heading"><h3 id="memories-title">Recalled memories</h3><span className="count-chip mono">{memories.length}</span></div><ol className="full-memory-list">{memories.map((memory) => <li key={`${memory.tier}-${memory.label}`}><div><MemoryTier tier={memory.tier} /><span className="mono source">{cleanCopy(memory.source)}</span></div><strong>{cleanCopy(memory.label)}</strong><p>{cleanCopy(memory.detail)}</p></li>)}{!memories.length ? <li className="memory-loading">{loading ? "Retrieving Sibyl memory" : "No recalled memories are available yet"}</li> : null}</ol></section>
        <section className="demo-panel decision-panel" data-view="receipt" aria-labelledby="decision-title"><div className="panel-heading"><h3 id="decision-title">Grounded recommendation</h3><span className="confidence mono">{Math.round((recommendation?.confidence ?? 0) * 100)}%</span></div><div className="recommendation-copy"><h4>{cleanCopy(recommendation?.action ?? "Waiting for recalled evidence")}</h4><p>{cleanCopy(recommendation?.rationale ?? "Relay will recompute the next action after the incident memory is loaded.")}</p>{recommendation?.blocked_actions?.length ? <div className="blocked-list"><span className="mono">Blocked by memory</span>{recommendation.blocked_actions.map((item) => <del key={item}>{cleanCopy(item)}</del>)}</div> : null}</div><div className={`session-receipt ${data?.is_fresh_session ? "is-active" : ""}`}><div><span className="receipt-check" aria-hidden="true">✓</span><span><strong>{data?.is_fresh_session ? "Fresh session receipt" : "Receipt not run"}</strong><small className="mono">{cleanCopy(data?.session_id ?? "waiting")}</small></span></div><dl><div><dt>Incident</dt><dd>{cleanCopy(incident.id)}</dd></div><div><dt>Memories recalled</dt><dd>{memories.length}</dd></div><div><dt>Status</dt><dd>{data?.is_fresh_session ? "ready" : "waiting"}</dd></div></dl></div></section>
      </div>
      <form className="evidence-form" onSubmit={submit} aria-labelledby="evidence-title"><div className="form-intro"><p className="eyebrow">Write to the incident memory</p><h3 id="evidence-title">Add live evidence</h3></div><label>Evidence type<select value={eventKind} onChange={(event) => setEventKind(event.target.value)}><option value="observation">Observation</option><option value="action">Action taken</option><option value="constraint">Operator constraint</option><option value="hypothesis">Hypothesis</option></select></label><label className="summary-field">What changed?<input value={eventSummary} onChange={(event) => setEventSummary(event.target.value)} placeholder={EVENT_HINTS[eventKind]} required minLength={3} maxLength={280} aria-describedby="summary-help" /><small id="summary-help">Use at least 3 characters. This is saved to Sibyl Memory.</small></label>{eventKind === "action" ? <label>Outcome<input value={eventOutcome} onChange={(event) => setEventOutcome(event.target.value)} placeholder="completed, blocked or no improvement" maxLength={280} /></label> : null}<button className="secondary-action save-action" disabled={pending === "event" || eventSummary.trim().length < 3}>{pending === "event" ? "Saving evidence" : "Save evidence"}</button></form>
    </section>
  );
}

function ProofSection({ data }) {
  return <section className="proof-section page-width" id="proof" aria-labelledby="proof-title"><div className="section-intro" data-reveal><p className="eyebrow">Technical proof</p><h2 id="proof-title">Memory you can inspect.</h2><p>Relay exposes the state, source and receipt behind every changed decision.</p></div><div className="proof-band" data-reveal><article><span className="proof-index mono">01</span><div><h3>Real Sibyl memory</h3><p>{cleanCopy(data?.memory_backend ?? "Sibyl Memory client")}</p></div></article><article><span className="proof-index mono">02</span><div><h3>Typed evidence ledger</h3><p>Every memory carries a tier, source and incident fact.</p></div></article><article><span className="proof-index mono">03</span><div><h3>Fresh session receipts</h3><p>Each test returns a new identifier and recalled memory count.</p></div></article></div></section>;
}

function FaqSection() {
  return <section className="faq-section page-width" id="faq" aria-labelledby="faq-title"><div className="section-intro" data-reveal><p className="eyebrow">Straight answers</p><h2 id="faq-title">Questions worth asking.</h2></div><div className="faq-list" data-reveal>{FAQS.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>;
}

function FinalCta({ onRun }) {
  return <section className="final-cta page-width" aria-labelledby="final-title" data-reveal><p className="eyebrow">Start with the proof</p><h2 id="final-title">Stop restarting the investigation.</h2><p>Run a fresh responder session, inspect what it recalls and see why the next action changes.</p><button className="primary-action" onClick={onRun}>Run the memory test <span aria-hidden="true">→</span></button></section>;
}

function SiteFooter() {
  return <footer className="site-footer page-width"><div><Brand /><p>Fresh incident memory for every new responder.</p></div><nav aria-label="Legal"><a href="/privacy">Privacy</a><a href="/terms">Terms</a></nav></footer>;
}

function LegalPage({ type }) {
  const isPrivacy = type === "privacy";
  return <main className="legal-page page-width"><a href="/" className="brand-link"><Brand /></a><p className="eyebrow">{isPrivacy ? "Privacy" : "Terms"}</p><h1>{isPrivacy ? "Relay privacy policy" : "Relay terms of use"}</h1><p>{isPrivacy ? "Relay processes the evidence you enter only to demonstrate incident memory. The local prototype stores incident data in the configured Sibyl Memory database and does not sell personal information." : "Relay is a hackathon prototype provided for evaluation. Do not use it as the sole authority for production incident decisions. Review every recommendation before acting."}</p><a className="primary-action link-action" href="/">Return to Relay</a></main>;
}

function NotFound() {
  return <main className="not-found page-width"><Brand /><p className="eyebrow">404 · Memory miss</p><h1>This route is not in the incident ledger.</h1><p>Return to the working Relay demo and run a fresh memory test.</p><a className="primary-action link-action" href="/">Return to Relay</a></main>;
}

export function App() {
  useRevealMotion();
  const [data, setData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [pending, setPending] = useState("");
  const [notice, setNotice] = useState("");
  const path = window.location.pathname;

  const loadDemo = async () => {
    setLoading(true); setError("");
    try { setData(await request("/api/demo")); }
    catch (caught) { setError(caught.message); }
    finally { setLoading(false); }
  };

  useEffect(() => { if (path === "/") loadDemo(); }, [path]);
  useEffect(() => {
    if (!notice) return undefined;
    const timeout = window.setTimeout(() => setNotice(""), 5200);
    return () => window.clearTimeout(timeout);
  }, [notice]);

  if (path === "/privacy" || path === "/terms") return <LegalPage type={path.slice(1)} />;
  if (path !== "/") return <NotFound />;

  const startFreshSession = async () => {
    document.getElementById("demo")?.scrollIntoView({ behavior: "smooth", block: "start" });
    if (!data || pending) return;
    setPending("session"); setError("");
    try {
      const next = await request(`/api/incidents/${data.incident.id}/sessions`, { method: "POST" });
      setData(next); setNotice(`${next.memories.length} memories loaded. The next action changed and the receipt is ready.`);
    } catch (caught) { setError(caught.message); }
    finally { setPending(""); }
  };

  const resetDemo = async () => {
    setPending("reset"); setError("");
    try { setData(await request("/api/demo/reset", { method: "POST" })); setNotice("The incident was restored to its prior session state."); }
    catch (caught) { setError(caught.message); }
    finally { setPending(""); }
  };

  const addEvent = async (payload) => {
    if (!data) return false;
    setPending("event"); setError("");
    try {
      setData(await request(`/api/incidents/${data.incident.id}/events`, { method: "POST", body: JSON.stringify(payload) }));
      setNotice("The evidence was saved to Sibyl Memory and the recommendation was recomputed.");
      return true;
    } catch (caught) { setError(caught.message); return false; }
    finally { setPending(""); }
  };

  return (
    <div className="app-shell">
      <a className="skip-link" href="#demo">Skip to the working demo</a>
      <SiteNav onRun={startFreshSession} />
      <main>
        <Hero data={data} loading={loading} onRun={startFreshSession} />
        <ProblemSection data={data} />
        <TaglineReveal />
        <HowItWorks />
        <div className="page-width demo-intro" data-reveal><p className="eyebrow">Working prototype</p><h2 id="demo-title">Run the memory test.</h2><p>Start a genuinely fresh session, inspect the recalled evidence and add a new incident fact.</p></div>
        {notice ? <div className="toast" role="status">{notice}</div> : null}
        <div className="page-width"><DemoConsole data={data} loading={loading} error={error} pending={pending} onRun={startFreshSession} onReset={resetDemo} onRetry={loadDemo} onAddEvent={addEvent} /></div>
        <ProofSection data={data} />
        <FaqSection />
        <FinalCta onRun={startFreshSession} />
      </main>
      <SiteFooter />
    </div>
  );
}
